image: local_java8

stages:
    - build

build_dev:
    stage: build
    only:
        - develop
    script:
        - mvn -U clean deploy sonar:sonar
        
build_prd:
    stage: build
    only:
        - master
    script:
        - mvn -U clean deploy sonar:sonar
        - maven-release
    