image: local_java8

stages:
    - build
    - deploy

build_dev:
    stage: build
    only:
        - develop
    script:
        - mvn -U clean deploy sonar:sonar
        
build_prd:
    stage: build
    only:
        - master
    script:
        - mvn -U clean deploy sonar:sonar
        
insight:
    stage: build
    except:
        - develop
        - master
    script:
        - mvn -U clean package sonar:sonar

deploy_test:
    image: local_ansible
    stage: deploy
    when: manual
    script:
        - echo "$VAULT_PASSWORD" > vault_password.txt
        - python3 /root/getPackage.py -r "libs-release-local/com/gardenlink/authentication" -m true -o app.jar
        - ansible-playbook -i deploy/inventories/prd --vault-password-file vault_password.txt -u administrateur deploy/playbook.yml