---
- name: Send file
  hosts: builder
  tasks:
    - name: copy key
      copy:
        content: "app.jar"
        dest: "app.jar"
        mode: 0600
  no_log: false
- name: Template a file to /etc/files.conf
  hosts: builder
  vars_files:
    - "{{inventory_dir}}/vars.yml"
    - "{{inventory_dir}}/secrets.yml"
  template:
    src: /templates/application.properties.j2
    dest: application.properties
    owner: administrateur
    mode: '0644'